version: '3.8'

services:
  tamani-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tamani-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
